add solution for second task
RomanNechaev/NaumenCollectionTask pull request #2
Opened 2023-04-01 12:26 UTC by RomanNechaev

1. Для эффективного подсчета слов использовал HashMap, т.к. он хэширует ключи и позволяет быстро находить ключ.
2. Сложность заполнения HashMap - O(n), сложность получения TOP 10 слов, и LAST 10 слов -- O(10), O(n) соответственно
3. Т.к нам нужно пройтись по всему файлу и инкриминировать уже обработанные слова, то сложность такой операции будет O(1) (поиск по ключу, в худшем случае O(n)), и итерация по всем словам в файле это еще n, итого в среднем за O(n), если hashcode дает мало коллизий, в худшем случае O(n^2).
4. Сортировка HashMap это O(logN)

2023-04-03 19:48 UTC, vpyzhyanov commented
А где итоговая сложность?

2023-04-03 19:52 UTC, vpyzhyanov commented
> 2\. сложность получения TOP 10 слов, и LAST 10 слов -- O(10), O(n) соответственно

Это очень долго!

> 3\. если hashcode дает мало коллизий

Никаких "если"! Что в вашем конкретно случае? Вы должны гарантировать сложность! Прошу чётко обосновать почему сложность именно такая.

2023-04-05 15:57 UTC, RomanNechaev commented
Изменил решение задачи.
1.Для эффективного подсчета слов использовал LinkedHashMap, т.к. он хэширует ключи и позволяет быстро находить ключ.
2.Сложность алгоритма выдачи TOP 10 и LAST 10 слов - O(n), Сложность заполнения LinkedHashMap - O(N*n), где N - кол-во слов в файле, n-уже обработанные слова в словаре. Итоговая сложность не хуже: O(N*n+n)
3.Т.к нам нужно пройтись по всему файлу и инкриминировать уже обработанные слова, то сложность такой операции будет не хуже O(n), и итерация по всем словам в файле это еще N, итого O(N*n). Получение статистки - O(n), т.к мы один раз пробегаемся по коллекции и налету формируем отсортированные коллекции, в которых получить первые 10 элементов занимает O(10).

2023-04-08 13:31 UTC, vpyzhyanov commented
> 1.Для эффективного подсчета слов использовал LinkedHashMap, т.к. он хэширует ключи и позволяет быстро находить ключ

Выбор правильный. Но обоснование страдает. Под это описание попадает лучше всего HashMap

2023-04-08 13:36 UTC, vpyzhyanov requested changes

2023-04-08 13:36 UTC, vpyzhyanov commented on pom.xml
> +            <version>2.11.0</version>
Зависимость определена не по правилам!

2023-04-08 13:36 UTC, vpyzhyanov commented on src/main/java/task2/WordsCount.java
> +                topTenWords.add(entry);
памяти вы, конечно, не жалеете. Впустую её тратите

2023-04-08 13:36 UTC, vpyzhyanov commented on src/main/java/task2/WordsCount.java
> +        LinkedHashMap<String, Long> numberOfWordInfile = new LinkedHashMap<>();
Испольование интерфейсов теперь обязательно.

2023-04-08 13:36 UTC, vpyzhyanov commented on src/main/resources/Лев_Толстой_Война_и_мир_Том_1,_2,_3,_4_(UTF-8).txt
В репозитории частных входных данных быть не должно. Тем более это большой файл! Неправильно относится к системе контроля версий как к файловому хранилищу!!!

2023-04-08 13:42 UTC, vpyzhyanov commented
> .Сложность алгоритма выдачи TOP 10 и LAST 10 слов - O(n), Сложность заполнения LinkedHashMap - O(N_n), где N - кол-во слов в файле, n-уже обработанные слова в словаре. Итоговая сложность не хуже: O(N_n+n)

По прежнему слишком долго. Да и сложность 

> Сложность заполнения LinkedHashMap - O(N_n), где N - кол-во слов в файле, n-уже обработанные слова в словаре._

Это что такое? Что за n? откуда взялось? Что-то я не знаком с такой математикой

2023-04-09 10:15 UTC, RomanNechaev commented
Вопрос 1. Всегда ли нужно оформлять pom по правилам? В данном случае, в первой попытке сдать задачу я посчитал не нужным это делать, т.к у нас один модуль и проект не предусматривает расширение.

 Изменил решение задачи:
1. Использовал HashMap, т.к он хэширует ключи и позволяет быстро находить их. Порядок вставки мне не важен, поэтому посчитал использование LinkedHashMap излишнем, тем более он использует больше памяти(из-за хранение ссылок). Использовал ArrayDeque т.к мне нужно за константное время получать первый и последний элемент, предварительно отсортировав очередь.
2. Сложность выдачи TOP 10 и LAST 10  элементов -  O(10). Сложность заполнения HashMap не хуже O(N*K), где N-кол-во всех слов в файле, K-кол-во элементов в HashMap. Сложность сортировки и заполнения ArrayDeque  - O(2nlogn). Суммарная сложность алгоритма не хуже O(N*K) + O(nlogn) + O(10)
3. Я не могу гарантировать, что на вход программе не подадут файл, который будет содержать слова, у которых одинаковый hashcode. Стандартная реализация hashcode у String хороша, но не идеальна. Поэтому отсюда и возникает сложность заполнения HashMap. Сложность заполнения ArrayDeque  - O(n) + сортировка O(nlogn) и того O(2nlogn). Сложность получения TOP 10 и LAST 10 в уже отсортированном ArrayDeque очевидна, т.к мы просто в цикле 10 раз получаем первый или последний элемент. Сложность получения первого и последнего элемента в ArrayDeque O(1).

2023-04-12 14:04 UTC, RomanNechaev commented
Ответ на вопрос: "Это что такое? Что за n? откуда взялось? Что-то я не знаком с такой математикой"
Это была опечатка + неоднозначно подобрал переменную под кол-во входных данных. Ниже я подробно объяснил, откуда это берется

 Изменил решение задачи:
1. Использовал LinkedHashMap, т.к он хэширует ключи и позволяет быстро находить их. Скорость итерации по LinkedHashMap быстрее, чем по HashMap. Хотя порядок вставки мне не важен, поэтому можно было бы использовать HashMap, но лучше пожертвовать памятью в угоду скорости. Использовал PriorityQueue т.к c помощью неё можно эффективно формировать TOP 10 и LAST 10 слов.
2. Сложность выдачи TOP 10 и LAST 10  элементов -  O(10). Сложность заполнения LinkedHashMap не хуже O(N), где N-кол-во всех слов в файле. Сложность формирования PriotutyQueue - O(n*log10), где n - кол-во элементов в LinkedHashMap. Суммарная сложность алгоритма не хуже O(N) + O(n*log10) + O(10) .
3. Сложность заполнения LinkedHashMap гарантируется тем, что в качестве ключа я использую String, у которого функция hashcode хорошо реализована и дает мало коллизий. Поэтому амортизационная сложность поиск элемента в LinkedHashMap - O(1), и соответственно, итоговая сложность формирования   LinkedHashMap - O(1)*O(N) = O(N).
Сложность формирования PriotutyQueue гарантируется тем, что алгоритм линейно 1 раз проходится по коллекции и  поддерживает размерность очереди равной 10, тем самым на каждой итерации очередь находится в упорядоченном состоянии.

2023-04-15 10:00 UTC, vpyzhyanov commented
Очень хорошо!

2023-04-16 07:55 UTC, merged