Task5
RomanNechaev/NaumenCollectionTask pull request #3
Opened 2023-04-01 12:35 UTC by RomanNechaev

1. Использую ArrayDeque, т.к нужно выдавать результаты в порядке передаче функций системе. 
2. O(1)
3. Т.к коллекция реализует паттерн FIFO, то легко получить последней элемент(все потому что ArrayDeque это двунаправленный linked list, который хранить ссылки на своих соседей в обе стороны)

2023-04-03 20:06 UTC, vpyzhyanov commented
> 1. Использую ArrayDeque, т.к нужно выдавать результаты в порядке передаче функций системе.

Нет обоснования. Под это описание подходят все коллекции интерфейса Queue и List.

> 2\. O(1)

Это не так

> 3\. ArrayDeque это двунаправленный linked list, который хранить ссылки на своих соседей в обе стороны

Это не так.

2023-04-03 20:11 UTC, vpyzhyanov requested changes

2023-04-03 20:11 UTC, vpyzhyanov commented on src/main/java/task5/ManagementSystem.java
> +        storage.addFirst(Map.entry(id, task));
Кажется вы перепутали первый и последний. А если не перепутали, то это попытка запутать других.

2023-04-03 20:11 UTC, vpyzhyanov commented on src/main/java/task5/ManagementSystem.java
> +        storage.addFirst(Map.entry(id, task));
стоит нескольким потокам обратиться к этому методу и весь этот карточный домик рухнет

2023-04-05 17:47 UTC, RomanNechaev commented
Изменил коллекцию на ConcurrentLinkedDeque
1.Нужно потокобезопасно и быстро получать результат выполнения функции, Deque обеспечивает FIFO и , соответственно, получение первого элемента за 0(1)
2. O(1)
3. реализация Queue обеспечивает получения первого элемента за O(1)

2023-04-08 13:47 UTC, vpyzhyanov commented
> Изменил коллекцию на ConcurrentLinkedDeque

Неоптимальный выбор коллекции. Подсказка: неоптимальный по памяти.

2023-04-09 13:38 UTC, RomanNechaev commented
Заменил на ConcurrentLinkedQueue. Действительно, для решения данной задачи интерфейс Deque не нужен, поэтому нет смысла создавать двунаправленный очередь и хранить "лишние" ссылки.

2023-04-16 07:56 UTC, merged